services:
  users_service:
    build: 
      context: ./user_service
      dockerfile: Dockerfile
    container_name: flask-api
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL="mysql+pymysql://admin:root@users_db:3306/users_db"
      - RABBITMQ_URL="amqp://guest:guest@rabbitmq:5672/"
    depends_on:
      users_db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
  
  users_db:
    image: mysql:9.1.0
    restart: always
    container_name: users_db
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    ports:
      - "3306:3306"
    volumes:
      - users_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Port dla komunikacji AMQP
      - "15672:15672" # UI RabbitMQ
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      retries: 5

volumes:
  users_db: