services:
  users_service:
    build: ./user_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL="mysql+pymysql://admin:root@localhost:3306/users_db"
    depends_on:
      - users_db 
  
  users_db:
    image: mysql:9.1.0
    restart: always
    environment:
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - users_db:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    ports:
    - "15672:15672"

volumes:
  users_db:
  users_service:
