openapi: 3.0.0
info:
  title: Flashcards App API
  version: 1.0.0
  description: API do zarządzania grupami, użytkownikami, zaproszeniami i fiszkami. Umożliwia tworzenie grup, zapraszanie członków, zarządzanie zaproszeniami i przeglądanie grup.
paths:
  /groups:
    post:
      summary: Tworzy nową grupę
      operationId: createGroup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                group_name:
                  type: string
                  example: "Grupa Matematyczna"
                description:
                  type: string
                  example: "Grupa do nauki matematyki"
              required:
                - group_name
      responses:
        '201':
          description: Grupa została pomyślnie utworzona
          content:
            application/json:
              schema:
                type: object
                properties:
                  group_id:
                    type: string
                    example: "201"
                  owner_id:
                    type: string
                    example: "1"
                  group_name:
                    type: string
                    example: "Grupa Matematyczna"
                  description:
                    type: string
                    example: "Grupa do nauki matematyki"
                  created_at:
                    type: string
                    example: "2024-11-09T12:00:00"
                  updated_at:
                    type: string
                    example: "2024-11-09T12:00:00"
        '400':
          description: Niepoprawne dane wejściowe (brak wymaganych parametrów)
          
  /groups/{group_id}/members:
    post:
      summary: Dodaje użytkownika do grupy
      operationId: addMemberToGroup
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
          example: "201"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_id:
                  type: string
                  example: "2"
              required:
                - user_id
      responses:
        '200':
          description: Użytkownik został dodany do grupy
          content:
            application/json:
              schema:
                type: object
                properties:
                  group_member_id:
                    type: string
                    example: "301"
                  group_id:
                    type: string
                    example: "201"
                  user_id:
                    type: string
                    example: "2"
                  added_at:
                    type: string
                    example: "2024-11-09T12:30:00"
        '403':
          description: Brak uprawnień do dodania członka (np. użytkownik nie jest właścicielem grupy)

  /groups/{group_id}/members/{user_id}:
    delete:
      summary: Usuwa członka z grupy
      operationId: removeMemberFromGroup
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
          example: "201"
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          example: "2"
      responses:
        '200':
          description: Użytkownik został usunięty z grupy
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User removed from the group successfully"
        '403':
          description: Brak uprawnień do usunięcia członka z grupy

  /users/{user_id}/groups:
    get:
      summary: Przeglądanie grup użytkownika
      operationId: getUserGroups
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: string
          example: "1"
      responses:
        '200':
          description: Lista grup, do których należy użytkownik
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    group_id:
                      type: string
                      example: "201"
                    owner_id:
                      type: string
                      example: "1"
                    group_name:
                      type: string
                      example: "Grupa Matematyczna"
                    description:
                      type: string
                      example: "Grupa do nauki matematyki"
                    created_at:
                      type: string
                      example: "2024-11-09T12:00:00"
                    updated_at:
                      type: string
                      example: "2024-11-09T12:30:00"
        '404':
          description: Brak grup dla użytkownika

  /groups/{group_id}:
    get:
      summary: Przeglądanie szczegółów grupy
      operationId: getGroupDetails
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
          example: "201"
      responses:
        '200':
          description: Szczegóły grupy
          content:
            application/json:
              schema:
                type: object
                properties:
                  group_id:
                    type: string
                    example: "201"
                  owner_id:
                    type: string
                    example: "1"
                  group_name:
                    type: string
                    example: "Grupa Matematyczna"
                  description:
                    type: string
                    example: "Grupa do nauki matematyki"
                  created_at:
                    type: string
                    example: "2024-11-09T12:00:00"
                  updated_at:
                    type: string
                    example: "2024-11-09T12:30:00"
                  members:
                    type: array
                    items:
                      type: object
                      properties:
                        user_id:
                          type: string
                          example: "2"
                        username:
                          type: string
                          example: "userB"
                        role:
                          type: string
                          example: "member"
        '404':
          description: Grupa nie znaleziona

  /groups/{group_id}/invitations:
    post:
      summary: Zapraszanie użytkowników do grupy
      operationId: sendGroupInvitation
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
          example: "201"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                recipient_id:
                  type: string
                  example: "2"
              required:
                - recipient_id
      responses:
        '200':
          description: Zaproszenie zostało wysłane
          content:
            application/json:
              schema:
                type: object
                properties:
                  invitation_id:
                    type: string
                    example: "301"
                  group_id:
                    type: string
                    example: "201"
                  sender_id:
                    type: string
                    example: "1"
                  recipient_id:
                    type: string
                    example: "2"
                  status:
                    type: string
                    example: "pending"
                  sent_at:
                    type: string
                    example: "2024-11-09T12:30:00"
        '400':
          description: Błąd w wysyłaniu zaproszenia

  /groups/{group_id}/invitations/{invitation_id}/accept:
    patch:
      summary: Akceptowanie zaproszenia do grupy
      operationId: acceptGroupInvitation
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
          example: "201"
        - name: invitation_id
          in: path
          required: true
          schema:
            type: string
          example: "301"
      responses:
        '200':
          description: Zaproszenie zostało zaakceptowane
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invitation accepted successfully"
        '404':
          description: Zaproszenie nie znalezione

  /groups/{group_id}/invitations/{invitation_id}/reject:
    patch:
      summary: Odrzucenie zaproszenia do grupy
      operationId: rejectGroupInvitation
      parameters:
        - name: group_id
          in: path
          required: true
          schema:
            type: string
          example: "201"
        - name: invitation_id
          in: path
          required: true
          schema:
            type: string
          example: "301"
      responses:
        '200':
          description: Zaproszenie zostało odrzucone
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invitation rejected successfully"
        '404':
          description: Zaproszenie nie znalezione

components:
  schemas:
    Group:
      type: object
      properties:
        group_id:
          type: string
        owner_id:
          type: string
        group_name:
          type: string
        description:
          type: string
        created_at:
          type: string
        updated_at:
          type: string
        members:
          type: array
          items:
            type: object
            properties:
              user_id:
                type: string
              username:
                type: string
              role:
                type: string
    Invitation:
      type: object
      properties:
        invitation_id:
          type: string
        group_id:
          type: string
        sender_id:
          type: string
        recipient_id:
          type: string
        status:
          type: string
        sent_at:
          type: string
        accepted_at:
          type: string
        rejected_at:
          type: string
"""

# Save the YAML content to a file
file_path = '/mnt/data/flashcards_api_documentation.yaml'

with open(file_path, 'w') as file:
    file.write(yaml_content)

file_path &#8203;:contentReference[oaicite:0]{index=0}&#8203;
